---
# tasks file for launch_windows_ami
- name: Get the VPC ID for {{ ec2_name_prefix }}-vpc
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: vpc_net_facts

- name: Set the VPC ID
  set_fact:
    vpc_id: "{{ vpc_net_facts.vpcs[0].id }}"

- name: Get the SG info for {{ ec2_name_prefix }}-vpc
  ec2_group_info:
    filters:
      vpc-id: "{{ vpc_id }}"
    region: "{{ ec2_region }}"
  register: group_info

- name: Select Public SG
  set_fact:
    group_id: "{{ group_info.security_groups | json_query(group_query) }}"
  vars:
    group_query: "[?group_name=='{{ ec2_name_prefix }}-Public-SG'].group_id"
  when: tier == "Public"

- name: Select Private SG
  set_fact:
    group_id: "{{ group_info.security_groups | json_query(group_query) }}"
  vars:
    group_query: "[?group_name=='{{ ec2_name_prefix }}-Private-SG'].group_id"
  when: tier == "Private"
    
- name: Get the subnet info for {{ ec2_name_prefix }}-vpc
  ec2_vpc_subnet_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
  register: subnet_info

- name: Select Subnet ID
  set_fact:
    subnet_id: "{{ subnet_info.subnets | json_query(subnet_query) | first }}"
  vars:
    subnet_query: "[?tags.Name=='{{ ec2_name_prefix }}-{{ tier }}-{{ zone }}'].subnet_id"

- name: "Find current, region-specific Windows AMI."
  ec2_ami_info:
    region: "{{ ec2_region }}"
    filters:
      name: "{{ ami_name }}"
  register: found_amis

- name: "Set AMI value"
  set_fact:
    win_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
  when: found_amis.images is defined

- name: "Start Windows instances."
  ec2:
    key_name: "{{ ec2_name_prefix }}-key"
    region: "{{ ec2_region }}"
    image: "{{ win_ami.image_id }}"
    instance_type: "{{ instance_type }}"
    group_id: "{{ group_id }}"
    vpc_subnet_id: "{{ subnet_id }}"
    wait: yes
    wait_timeout: 500
    exact_count: 1
    count_tag: 
      Name: "{{ instance_tag_inventory }} Windows Server {{ item }}"
    instance_tags:
      Role: windows_server
      Platform: Windows
      Name: "{{ instance_tag_inventory }} Windows Server {{ item }} "
      Inventory: "{{ instance_tag_inventory }}"
      Stage: "instantiated"
    user_data: "{{ lookup('template', '{{ role_path }}/templates/userdata.txt.j2') }}"
  loop: "{{ range(1, instance_count +1)|list }}"
  loop_control:
    label: "{{ item }}"
  register: ec2

- name: "Wait for connection on all hosts."
  wait_for:
    host: "{{ item['tagged_instances'][0]['private_ip'] }}"
    port: 5986
    timeout: 500
  loop: "{{ ec2.results }}"
  loop_control:
    label: "{{ item['tagged_instances'][0]['private_ip'] }}"

- name: Show private DNS name
  debug:
    msg: "Private DNS name: {{ item.private_dns_name }}"
  loop: "{{ ec2_result.instances }}"

